### ISSUE TITLE
缺少组件

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/switch-static-and-dynamic-page#3]
有的 widget 找不到  https://wiki.onetwo.ren/%E5%8A%A8%E6%80%81%E6%95%B0%E6%8D%AE%E4%BB%98%E8%B4%B9%E5%88%9B%E6%84%8F%E5%B7%A5%E5%9D%8A%E7%BA%BF%E4%B8%8A%E7%BA%BF%E4%B8%8B%E5%88%86%E7%B1%BB%E9%A1%B9%E7%9B%AE

大部分的宏都找不到 https://wiki.onetwo.ren/Index

**Comment by oeyoews** [comment]
静态功能只能呈现静态文本，就像没有了js的HTML， 我的wiki大多依赖widget，后来觉得麻烦，要同时维护两个界面，就不搞静态界面了

**Comment by linonetwo** [comment]
哦对，想起来很多 Widget 没考虑静态使用，都是动态创建的东西，估计得改造一下。 可能得用 $tw.utils.domMaker 什么的官方 api 才行。

但是有的 宏 也没了就很奇怪，比如 shiraz 的 details 宏，用来折叠内容的，也不见了

**Comment by linonetwo** [comment]
不对，我觉得是被遮挡了或者吞了，因为这个文本也不见了

`注意[[早睡早起]]`

<img width="1460" alt="截屏2023-10-27 17 39 44" src="https://github.com/tiddly-gittly/switch-static-and-dynamic-page/assets/3746270/c0cd1534-e181-4752-8af5-126f9ac96159">

**Comment by oeyoews** [comment]
静态下没有window对象, domMaker 也用到了 document, 刚才看了一下fakedom, 静态下用的就是这个简化版的dom, 只能保证一些核心的widget运行. 那些模板应该就是用到了这些widget

**Comment by oeyoews** [comment]
https://tiddlywiki.com/dev/#FakeDomMechanism

**Comment by linonetwo** [comment]
是 echarts 的问题，原因不明

https://github.com/tiddly-gittly/tw-echarts/issues/103
